services:
  - type: web
    name: hello-spring
    env: docker
    # Build from Dockerfile instead of registry image
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      # Ping Service Configuration
      - key: PING_ENABLED
        value: true
      - key: PING_URL
        value: https://hello-spring-latest.onrender.com  # Update with your actual URL
      - key: PING_INTERVAL
        value: 5
      - key: PING_LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - mvnw
        - mvnw.cmd
        - Dockerfile
        - .dockerignore
    previewsEnabled: true
    # Resource allocation for better performance
    plan: free