services:
  - type: web
    name: hello-spring
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/hello_spring-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0"
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - mvnw
        - mvnw.cmd
    previewsEnabled: true