services:
  - type: web
    name: hello-spring
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - mvnw
        - mvnw.cmd
        - Dockerfile
        - .dockerignore
    previewsEnabled: true
    # Resource allocation for better performance
    plan: starter